"""Telemetry Pydantic schemas for data validation."""
from typing import Optional, Any
from pydantic import BaseModel, Field

# --- Session Ingestion Schemas ---
class SessionStartRequest(BaseModel):
    session_id: str = Field(..., description="Unique session ID generated by game client")
    persona_type: str = Field(default="HUMAN", description="HUMAN, BEGINNER, EXPLORER, SPEEDRUNNER, or AGGRESSIVE")
    level_name: str = Field(default="Level_1", description="Level currently being played")
    game_version: str = Field(default="1.0.0", description="Game build version")

class SessionStartResponse(BaseModel):
    status: str
    session_id: str
    message: str

class SessionEndRequest(BaseModel):
    session_id: str
    status: str = Field(..., description="COMPLETED, FAILED, or ABORTED")
    duration_seconds: float = Field(default=0.0, ge=0.0)
    total_score: int = Field(default=0)
    total_deaths: int = Field(default=0)
    items_collected: int = Field(default=0)
    enemies_defeated: int = Field(default=0)

class SessionEndResponse(BaseModel):
    status: str
    session_id: str
    final_status: str
    duration_seconds: float

# --- Position Schemas ---
class PositionSampleCreate(BaseModel):
    timestamp: float = Field(..., ge=0.0, description="Seconds elapsed in level")
    x: float
    y: float
    z: float = 0.0
    health: int = Field(default=100, ge=0)

class PositionBatchRequest(BaseModel):
    session_id: str
    level_name: Optional[str] = "Level_1"
    positions: list[PositionSampleCreate]

# --- Event Schemas ---
class GameplayEventCreate(BaseModel):
    session_id: str
    event_type: str = Field(..., description="DEATH, CHECKPOINT, ITEM_PICKUP, ENEMY_KILLED, DAMAGE_TAKEN")
    level_name: Optional[str] = "Level_1"
    timestamp: float
    x: float
    y: float
    z: float = 0.0
    cause_or_source: Optional[str] = Field(default=None, description="e.g. Spike_Pit, Archer, Health_Potion")
    additional_data: Optional[dict[str, Any]] = None

class GenericBatchResponse(BaseModel):
    status: str
    records_saved: int
